name: CD
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: so1s
          password: ${{ secrets.GH_TOKEN }}
      - name: Find-and-replace strings
        uses: mad9000/actions-find-and-replace-string@2
        id: replace_version
        with:
          source: ${{ github.ref_name }}
          find: 'v'
          replace: ''
      - name: Check Release
        uses: haya14busa/action-cond@v1.0.0
        id: version
        with:
          cond: ${{ startsWith(github.ref_name, 'v')  }}
          if_true: ${{ steps.replace_version.outputs.value }}
          if_false: "latest"
      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/so1s/frontend:${{ steps.version.outputs.value }}