name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: so1s
          password: ${{ secrets.GH_TOKEN }}
      - name: Conditional value for GitHub Action
        uses: haya14busa/action-cond@v1.0.0
        id: checkRelease
        with:
          cond: ${{ startsWith(github.ref_name, 'release')  }}
          if_true: ${{ join(github.ref_name, '/')[1] }}
          if_false: "latest"
      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ !startsWith(github.ref_name, 'release')  }}
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/so1s/frontend:${{ steps.checkRelease.outputs.value }}