name: CI
on: pull_request

jobs:
  lint:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/setup-node@v2
        name: setup node
        with:
          node-version: '18'
      - uses: actions/cache@v3
        name: install cache
        with:
          path: ./.yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: install dependency
        run: |
          npm i -g yarn
          yarn set version stable
          yarn install --immutable --immutable-cache
      - name: run lint
        run: yarn lint
        