name: CI
on: pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/setup-node@v2
        name: setup node
        with:
          node-version: '18'
          cache: 'yarn'
      - name: install dependency
        run: yarn install --immutable --immutable-cache
      - name: run lint
        run: yarn lint
      - name: run test
        run: yarn test
        